import markdown
from django import template
from django.db.models import Count
from django.utils.safestring import mark_safe

from blog.models import Post

register = template.Library()


@register.simple_tag  # (name="my_tag") to use the function with a different name inside templates
def total_posts():
    return Post.published.count()


@register.inclusion_tag("blog/post/latest_posts.html")
def show_latest_posts(count=5):
    latest_posts = Post.published.order_by("-publish")[:count]
    return {"latest_posts": latest_posts}


@register.simple_tag
def get_most_commented_posts(count=5):
    return Post.published.annotate(total_comments=Count("comments")).order_by(
        "-total_comments"
    )[:count]


@register.filter(name="markdown")  # We prevent a name clash with the markdown module
def markdown_format(text):
    # By default, Django escape the HTML characters generated by filters
    return mark_safe(markdown.markdown(text))
